### ISSUE TITLE
Parsing a VCF file headers into a data structure

### ISSUE THREAD

**Issue by figueroakl** [Rust-Wellcome/vcf-parser#14]
**User Story**

As Developers we would like to parse the VCF file headers into a data structure so that ...

**Acceptance Criteria**

To be considered successful the solution must allow: 
- [ ] The parsing of the headers into a data structure. What type? e.g. Rust Struct or standard JSON ...
- [ ] Validation of the headers to ensure they contain a FileFormat header on the first line
- [ ] Validation of the headers to ensure that they contain a valid FileFormat version e.g. v4.0
- [ ] The separation of each unstructured header into a key-value pair
- [ ] The separation of each structured header into a key-value pair
- [ ] The nesting of each duplication value of the structured heading with the key for that value being the ID of the header.
- [ ] The separation of each value for each structured header into it's constituent parts which will be the Number, the data type e.g. Integer and it's description.

**Additional Context**
- A header row is one which has a double hash ('##') at the beginning of the line
- An unstructured header row is one which contains a key and a value separated by an equals sign ('=')
- A structured header row is one which has a key and value separated by the equals sign ('=') where the value is surrounded by angle brackets ('< >') and the first item within the brackets is ID and each item within the brackets is separated by a comma (',')

***Example file*** (can't save as vcf as github doesn't support it)

- [vcf-snapshot.vcf.txt](https://github.com/Rust-Wellcome/vcf-parser/files/10965980/vcf-snapshot.vcf.txt)

***Example VCF standards***
- VCF4.0 - https://www.internationalgenome.org/wiki/Analysis/vcf4.0/
- VCF4.4 - https://samtools.github.io/hts-specs/VCFv4.4.pdf

**Comment by stevieing** [comment]
Example file:
[vc-snapshot.vcf.txt](https://github.com/Rust-Wellcome/vcf-parser/files/10965784/vc-snapshot.vcf.txt)

**Comment by stevieing** [comment]
Example file (can't save as vcf as github doesn't support it.
[vcf-snapshot.vcf.txt](https://github.com/Rust-Wellcome/vcf-parser/files/10965980/vcf-snapshot.vcf.txt)

**Comment by stevieing** [comment]
Example file VCF4 with description and structure https://www.internationalgenome.org/wiki/Analysis/vcf4.0/

**Comment by stevieing** [comment]
My initial thoughts:

- Each file has a version number
- There are several header types e.g. format, info, contig
- Each header type has particular attributes e.g.
- format - id, number, type, description 
- Info - id, number, type, description
- contig - id, length

**Comment by stevieing** [comment]
Task list:

- [ ] create a parser library

**Comment by jeff-k** [comment]
so the spec says header lines can be either "unstructured" key-value pairs:
```
##fileformat=VCFv4.4
##fileDate=20230218
##source=MyProgram-v0.1
```
or "structured":
```
##INFO=<ID=NS,...>
##INFO=<ID=AA,...>
```
where the keys may be non-unique and the values are `<>`-bracketed key-value pairs. The keys with specified meanings are `INFO`, `FORMAT`, and `FILTER`.

I think the most general solution is for the header struct to have a hashmap with these key-value pairs loaded in, and in cases where there may be non-unique keys, such as the `INFO` lines, the value for the `INFO` key would a nested hashmap that's keyed with the `ID` values.

This is assuming that only the unstructured lines can have non-unique keys, and that all unstructured key-value pairs include an `ID` member. The latter point is explicitly stated in the spec.

In JSON, the nested hashmap for a file with the above lines would look like:
```json
{
"fileformat": "VCFv4.4",
"fileDate": 20230218,
"source": "MyProgram-v0.1",
"INFO": {
    "NS": { ... },
    "AA": { ... },
}
```
